<?php


namespace app\Controller\Agent\V1;


use app\Controller\Agent\ApiBaseController;
use app\Services\Agent\AgentService;

class AgentController extends ApiBaseController
{
	public $agentService;
	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->agentService = new AgentService();
	}
	
	public function index()
	{
		$rule = [
			'name' => ['require|string', 'require' => 100]
		];
		if(!$res = $this->validateInput($rule)){
			return $this->responseData();
		}
		$data = $this->agentService->index($this->input);
		return $this->responseData($data);
	}
	
	public function show()
	{
	
	}
	
	public function store()
	{
	
	}
	
	public function update()
	{
	
	}
	
	public function destroy()
	{
	
	}
}