<?php


namespace app\Controller\Develop\V1;


use app\Controller\Develop\ApiBaseController;
use app\Services\Develop\DataService;

class DataController extends ApiBaseController
{
	public $dataService;
	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->dataService = new DataService();
	}
	
	/**
	 * 同步管理员
	 */
	public function store()
	{
		$rule = [
			'agent_uid'   => ['require', 'require' => 1006 ],
			'type'  => ['require', 'require' => 1007],
			'data'   => ['require', 'require' => 1009],
			'md5'    =>  ['require', 'require' => 1011],
		];
		if (!$this->validateInput($rule)) {
			return $this->responseData();
		}
		$data = $this->dataService->store($this->develop, $this->input);
		return $this->responseData($data);
	}
}